<Project Sdk="Microsoft.NET.Sdk">

  <!-- ============== core settings ============== -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>false</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Argyle.glTF2BIM</AssemblyName>
    <Configurations>Debug;Release;Release2025;Release2026;Debug2025;Debug2026</Configurations>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <!-- ============== 2025 build configuration ============== -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2025|Any CPU'">
    <OutputPath>..\..\..\build\Release2025\</OutputPath> <!-- mirrors legacy layout -->
    <DefineConstants>REVIT;REVIT2025</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2025|Any CPU'">
    <OutputPath>..\..\..\build\Release2025\</OutputPath>
    <DefineConstants>REVIT;REVIT2025</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2026|Any CPU'">
    <OutputPath>..\..\..\build\Release2026\</OutputPath>
    <DefineConstants>REVIT;REVIT2026</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <!-- ============== 2026 build configuration ============== -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2026|Any CPU'">
    <OutputPath>..\..\..\build\Release2026\</OutputPath> <!-- mirrors legacy layout -->
    <DefineConstants>REVIT;REVIT2026</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <!-- ============== source sharing ============== -->
  <ItemGroup>
    <Compile Include="..\GLTF2BIM\**\*.cs" Exclude="..\GLTF2BIM.Net8\**\*.*;&#xD;&#xA;                      ..\GLTF2BIM\obj\**\*.*;&#xD;&#xA;                      ..\GLTF2BIM\bin\**\*.*;&#xD;&#xA;                      ..\GLTF2BIM\**\*.g.cs;&#xD;&#xA;                      ..\GLTF2BIM\**\*.g.i.cs" />
                      
    <EmbeddedResource Include="..\GLTF2BIM\**\*.resx" Exclude="..\GLTF2BIM\obj\**\*.*;&#xD;&#xA;                              ..\GLTF2BIM\bin\**\*.*" />
  </ItemGroup>


  <!-- ============== NuGet ============== -->
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
